# Homework 2: Arrays and Tables (50 points)

Please complete this notebook by filling in the cells provided. The solved homework should be uploaded to Canvas.

**Reading**: 

Data8 textbook chapters [2](http://www.inferentialthinking.com/chapters/02/causality-and-experiments), [4](http://www.inferentialthinking.com/chapters/04/data-types.html), [5](http://www.inferentialthinking.com/chapters/05/sequences.html) and [6](http://www.inferentialthinking.com/chapters/06/tables.html).

**Deadline**:

**This assignment is due on Wednesday, October 17 at 2:00pm.** Late work will not be accepted unless you have made special arrangements with the instructors.

Directly sharing answers is not okay, but discussing problems with the course staff or with other students is encouraged.

You should start early so that you have time to get help if you're stuck.


In [1]:
# Don't change this cell; just run it. 

import numpy as np
from datascience import *


## 1. Studying the Survivors (6 points)


The Reverend Henry Whitehead was skeptical of John Snow’s conclusion about the Broad Street pump (see Chapter 2 of the textbook that is part of your reading assignment above). After the Broad Street cholera epidemic ended, Whitehead set about trying to prove Snow wrong.  (The history of the event is detailed [here](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC1034367/pdf/medhist00183-0026.pdf).)

He realized that Snow had focused his analysis almost entirely on those who had died. Whitehead, therefore, investigated the drinking habits of people in the Broad Street area who had not died in the outbreak.

What is the main reason it was important to study this group?

1) If Whitehead had found that many people had drunk water from the Broad Street pump and not caught cholera, that would have been evidence against Snow's hypothesis.

2) Survivors could provide additional information about what else could have caused the cholera, potentially unearthing another cause.

3) Through considering the survivors, Whitehead could have identified a cure for cholera.

In [2]:
# Set survivor_answer to 1, 2, or 3
survivor_answer = 1

**Note:** Whitehead ended up finding further proof that the Broad Street pump played the central role in spreading the disease to the people who lived near it. Eventually, he became one of Snow’s greatest defenders.

## 2. Creating Arrays (6 points)


**Question 1.** Make an array called `weird_numbers` containing the following numbers (in the given order):

1. -2
2. the sine of 1.2
3. 3
4. 5 to the power of the cosine of 1.2

*Hint:* `sin` and `cos` are functions in the `math` module.

In [3]:
# Our solution involved one additional line of code before creating weird_numbers.
# Replace "..." with your code
import math
weird_numbers = make_array(-2, math.sin(1.2), 3, 5**(math.cos(1.2)))
weird_numbers

array([-2.        ,  0.93203909,  3.        ,  1.79174913])

**Question 2.** Make an array called `book_title_words` containing the following three strings: "Eats", "Shoots", and "and Leaves".

In [4]:
book_title_words = make_array("Eats", "Shoots", "and Leaves")
book_title_words

array(['Eats', 'Shoots', 'and Leaves'], dtype='<U10')

Strings have a method called `join`.  `join` takes one argument, an array of strings.  It returns a single string.  Specifically, the value of `a_string.join(an_array)` is a single string that's the [concatenation](https://en.wikipedia.org/wiki/Concatenation) ("putting together") of all the strings in `an_array`, **except** `a_string` is inserted in between each string

**Question 3.** Use the array `book_title_words` and the method `join` to make two strings:

1. "Eats, Shoots, and Leaves" (call this one `with_commas`)
2. "Eats Shoots and Leaves" (call this one `without_commas`)

*Hint:* If you're not sure what `join` does, first try just calling, for example, `"foo".join(book_title_words)` .

In [5]:
with_commas = ", ".join(book_title_words)
without_commas = " ".join(book_title_words)

# These lines are provided just to print out your answers.
print('with_commas:', with_commas)
print('without_commas:', without_commas)

with_commas: Eats, Shoots, and Leaves
without_commas: Eats Shoots and Leaves


## 3. Indexing Arrays (8 points)


These exercises give you practice accessing individual elements of arrays.  In Python (and in many programming languages), elements are accessed by *index*, so the first element is the element at index 0.  

**Question 1.** The cell below creates an array of some numbers.  Set `third_element` to the third element of `some_numbers`.

In [6]:
some_numbers = make_array(-1, -3, -6, -10, -15)

third_element = some_numbers[2]
third_element

-6

**Question 2.** The next cell creates a table that displays some information about the elements of `some_numbers` and their order.  Run the cell to see the partially-completed table, then fill in the missing information in the cell (the strings that are currently "???") to complete the table.

In [7]:
elements_of_some_numbers = Table().with_columns(
    "English name for position", make_array("first", "second", "third", "fourth", "fifth"),
    "Index",                     make_array("0", "1", "2", "3", "4"),
    "Element",                   some_numbers)
elements_of_some_numbers

English name for position | Index | Element
first                     | 0     | -1
second                    | 1     | -3
third                     | 2     | -6
fourth                    | 3     | -10
fifth                     | 4     | -15

**Question 3.** You'll sometimes want to find the *last* element of an array.  Suppose an array has 142 elements.  What is the index of its last element?

In [8]:
index_of_last_element = 141

More often, you don't know the number of elements in an array, its *length*.  (For example, it might be a large dataset you found on the Internet.)  The function `len` takes a single argument, an array, and returns the `len`gth of that array (an integer).

**Question 4.** The cell below loads an array called `president_birth_years`.  The last element in that array is the most recent birth year of any deceased president. Assign that year to `most_recent_birth_year`.

In [9]:
president_birth_years = Table.read_table("president_births.csv").column('Birth Year')

most_recent_birth_year = Table.read_table("president_births.csv").column('Birth Year').item(-1)
most_recent_birth_year

1917

## 4. Basic Array Arithmetic (10 points)


**Question 1.** Multiply each of the numbers 42, 4224, 42422424, and -250 by 157.  For this question, **don't** use arrays.

In [10]:
first_product = 42*157
second_product = 4224*157
third_product = 42422424*157
fourth_product = -250*157
print(first_product, second_product, third_product, fourth_product)

6594 663168 6660320568 -39250


**Question 2.** Now, do the same calculation, but using an array called `numbers` and only a single multiplication (`*`) operator.  Store the 4 results in an array named `products`.

In [11]:
numbers = make_array(42, 4224, 42422424, -250)
products = numbers * 157
products

array([      6594,     663168, 6660320568,     -39250])

**Question 3.** Oops, we made a typo!  Instead of 157, we wanted to multiply each number by 1577.  Compute the new products in the cell below using array arithmetic.  Notice that your job is really easy if you previously defined an array containing the 4 numbers.

In [12]:
new_products = numbers * 1577
new_products

array([      66234,     6661248, 66900162648,     -394250])

**Question 4.** We've loaded an array of temperatures in the next cell.  Each number is the highest temperature observed on a day at a climate observation station, mostly from the US.  Since they're from the US government agency [NOAA](noaa.gov), all the temperatures are in Fahrenheit.  Convert them all to Celsius by first subtracting 32 from them, then multiplying the results by $\frac{5}{9}$. Round each result to the nearest integer using the `np.round` function.

In [13]:
max_temperatures = Table.read_table("temperatures.csv").column("Daily Max Temperature")

celsius_max_temperatures = np.round((5/9)*(max_temperatures - 32))
celsius_max_temperatures


array([-4., 31., 32., ..., 17., 23., 16.])

**Question 5.** The cell below loads all the *lowest* temperatures from each day (in Fahrenheit).  Compute the size of the daily temperature range for each day.  That is, compute the difference between each daily maximum temperature and the corresponding daily minimum temperature.  **Give your answer in Celsius!**

In [14]:
min_temperatures = Table.read_table("temperatures.csv").column("Daily Min Temperature")

celsius_temperature_ranges = celsius_max_temperatures - (np.round((5/9)*(min_temperatures - 32)))
celsius_temperature_ranges

array([ 7., 10., 13., ..., 18., 12., 11.])

## 5. Old Faithful (8 points)


Old Faithful is a geyser in Yellowstone that erupts every 44 to 125 minutes (according to [Wikipedia](https://en.wikipedia.org/wiki/Old_Faithful)). People are [often told that the geyser erupts every hour](http://yellowstone.net/geysers/old-faithful/), but in fact the waiting time between eruptions is more variable. Let's take a look.

**Question 1.** The first line below assigns `waiting_times` to an array of 272 consecutive waiting times between eruptions, taken from a classic 1938 dataset. Assign the names `shortest`, `longest`, and `average` so that the `print` statement is correct.

In [15]:
waiting_times = Table.read_table('old_faithful.csv').column('waiting')

shortest = waiting_times.min()
longest = waiting_times.max()
average = np.round(sum(waiting_times)/len(waiting_times))

print("Old Faithful erupts every", shortest, "to", longest, "minutes and every", average, "minutes on average.")

Old Faithful erupts every 43 to 96 minutes and every 71.0 minutes on average.


**Question 2.** Assign `biggest_decrease` to the biggest descrease in waiting time between two consecutive eruptions. For example, the third eruption occurred after 74 minutes and the fourth after 62 minutes, so the decrease in waiting time was 74 - 62 = 12 minutes. *Hint*: You'll need an array arithmetic function [mentioned in the textbook](https://www.inferentialthinking.com/chapters/04/4/arrays.html#Functions-on-Arrays).

In [16]:
biggest_decrease = np.diff(waiting_times).max()
biggest_decrease

47

**Question 3.** If you expected Old Faithful to erupt every hour, you would expect to wait a total of `60 * k` minutes to see `k` eruptions. Set `difference_from_expected` to an array with 272 elements, where the element at index `i` is the absolute difference between the expected and actual total amount of waiting time to see the first `i+1` eruptions.  *Hint*: You'll need to compare a cumulative sum (that is, for each element add all the elements so far) to a range.  Numpy has a function to do this for you.

For example, since the first three waiting times are 79, 54, and 74, the total waiting time for 3 eruptions is 79 + 54 + 74 = 207. The expected waiting time for 3 eruptions is 60 * 3 = 180. Therefore, `difference_from_expected.item(2)` should be $|207 - 180| = 27$.

In [53]:
expected_times = np.arange(60, 60*273, 60)
cumulative = np.cumsum(waiting_times)
difference_from_expected = abs(cumulative - expected_times)


**Question 4.** If instead you guess that each waiting time will be the same as the previous waiting time, how many minutes would your guess differ from the actual time, averaging over every wait time except the first one.

For example, since the first three waiting times are 79, 54, and 74, the average difference between your guess and the actual time for just the second and third eruption would be $\frac{|79-54|+ |54-74|}{2} = 22.5$.

In [85]:
average_error = np.cumsum(np.abs(np.diff(waiting_times)))/np.arange(1, 272, 1)
average_error


array([25.        , 22.5       , 19.        , 20.        , 22.        ,
       23.83333333, 20.85714286, 22.5       , 23.77777778, 24.5       ,
       25.        , 23.41666667, 24.        , 24.85714286, 25.26666667,
       24.3125    , 24.17647059, 24.61111111, 24.73684211, 24.9       ,
       23.9047619 , 24.22727273, 23.56521739, 22.79166667, 22.24      ,
       22.46153846, 22.40740741, 21.67857143, 20.96551724, 20.46666667,
       19.93548387, 19.65625   , 19.48484848, 19.08823529, 19.17142857,
       18.75      , 19.10810811, 19.15789474, 19.46153846, 19.225     ,
       19.29268293, 19.45238095, 19.60465116, 19.5       , 19.28888889,
       19.2826087 , 19.10638298, 19.3125    , 19.3877551 , 19.32      ,
       19.23529412, 19.55769231, 19.67924528, 19.7962963 , 19.96363636,
       19.82142857, 19.59649123, 19.48275862, 19.22033898, 19.26666667,
       19.36065574, 19.62903226, 19.85714286, 19.890625  , 20.07692308,
       19.98484848, 19.68656716, 19.58823529, 19.42028986, 19.27

## 6. Tables (12 points)


**Question 1.** Suppose you have 4 apples, 3 oranges, and 3 pineapples.  (Perhaps you're using Python to solve a high school Algebra problem.)  Create a table that contains this information.  It should have two columns: "fruit name" and "count".  Give it the name `fruits`.

**Note:** Use lower-case and singular words for the name of each fruit, like `"apple"`.

In [19]:
fruits = Table().with_columns(
    'Fruit Name', make_array('Apples', 'Oranges', 'Pineapples'),
    'Count', make_array(4, 3, 3)
)
fruits

Fruit Name | Count
Apples     | 4
Oranges    | 3
Pineapples | 3

**Question 2.** The file `inventory.csv` contains information about the inventory at a fruit stand.  Each row represents the contents of one box of fruit.  Load it as a table named `inventory`.

In [20]:
inventory = Table.read_table("inventory.csv")
inventory

box ID | fruit name | count
53686  | kiwi       | 45
57181  | strawberry | 123
25274  | apple      | 20
48800  | orange     | 35
26187  | strawberry | 255
57930  | grape      | 517
52357  | strawberry | 102
43566  | peach      | 40

**Question 3.** The file `sales.csv` contains the number of fruit sold from each box last Saturday.  It has an extra column called "price per fruit (\$)" that's the price *per item of fruit* for fruit in that box.  The rows are in the same order as the `inventory` table.  Load the file into a table called `sales`.

In [21]:
sales = Table.read_table("sales.csv")
sales

box ID | fruit name | count sold | price per fruit ($)
53686  | kiwi       | 3          | 0.5
57181  | strawberry | 101        | 0.2
25274  | apple      | 0          | 0.8
48800  | orange     | 35         | 0.6
26187  | strawberry | 25         | 0.15
57930  | grape      | 355        | 0.06
52357  | strawberry | 102        | 0.25
43566  | peach      | 17         | 0.8

**Question 4.** How many fruits did the store sell in total on that day?

In [22]:
total_fruits_sold = sum(sales.column('count sold'))
total_fruits_sold

638

**Question 5.** What was the store's total revenue (the total price of all fruits sold) on that day?

*Hint:* If you're stuck, think first about how you would compute the total revenue from just the grape sales.

In [23]:
total_revenue = sum(sales.column('count sold') * sales.column('price per fruit ($)'))
total_revenue

106.85

**Question 6.** Make a new table called `remaining_inventory`.  It should have the same rows and columns as `inventory`, except that the amount of fruit sold from each box should be subtracted from that box's count, so that the "count" is the amount of fruit remaining after Saturday.

In [24]:
remaining_inventory = Table().with_columns(
    "box ID", inventory.column('box ID'),
    "fruit name", inventory.column('fruit name'),
    "count", inventory.column('count') - sales.column('count sold')
)
remaining_inventory

box ID | fruit name | count
53686  | kiwi       | 42
57181  | strawberry | 22
25274  | apple      | 20
48800  | orange     | 0
26187  | strawberry | 230
57930  | grape      | 162
52357  | strawberry | 0
43566  | peach      | 23